### ISSUE TITLE
`export_font_style` is not supported.

### ISSUE THREAD

**Issue by raiyankamal** [ShayHill/docx2python#18]
# Observed behaviour
According to [the docs](https://docx2python.readthedocs.io/en/latest/index.html#use) `export_font_style`  is an argument accepted by method `docx2python`. But calling this method with this argument results in TypeError.

    doc = docx2python(local_file_path, html=True, export_font_style=False)

Leads to error:

    TypeError: docx2python() got an unexpected keyword argument 'export_font_style'

Furthermore, in the source code of `docx2python` we can see this parameter does not exist.

https://github.com/ShayHill/docx2python/blob/21b2edafc0a01a6cfb73aefc61747a65917e2cad/docx2python/main.py#L19

Searching for this in the entire repository, I found out only mentions of this parameter in docs.
https://github.com/ShayHill/docx2python/search?q=export_font_style

Currently, the output of `docx2python(local_file_path, html=True)` has `<`, `>` symbols are replaced by as `&gt;`, `&lt;` respectively.

# Expected behaviour

`export_font_style` should be supported and behave according to the docs.

**Comment by ShayHill** [comment]
Thank you for the report. `export_font_style` was an earlier name for `html=True`, so this is a documentation error. I am going to leave this one open and perhaps incorporate a fix into one more release of Docx2Python v1. However, I am currently testing Docx2Python v2 and will focus the majority of my efforts there.

What additional support for font styles would you like to see?

-Shay

From: Raiyan ***@***.***>
Sent: Thursday, July 1, 2021 6:35 AM
To: ShayHill/docx2python ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ShayHill/docx2python] `export_font_style` is not supported. (#18)

Observed behaviour

According to the docs<https://docx2python.readthedocs.io/en/latest/index.html#use> export_font_style is an argument accepted by method docx2python. But calling this method with this argument results in TypeError.

doc = docx2python(local_file_path, html=True, export_font_style=False)

Leads to error:

TypeError: docx2python() got an unexpected keyword argument 'export_font_style'

Furthermore, in the source code of docx2python we can see this parameter does not exist.

https://github.com/ShayHill/docx2python/blob/21b2edafc0a01a6cfb73aefc61747a65917e2cad/docx2python/main.py#L19

Searching for this in the entire repository, I found out only mentions of this parameter in docs.
https://github.com/ShayHill/docx2python/search?q=export_font_style

Currently, the output of docx2python(local_file_path, html=True) has <, > symbols are replaced by as &gt;, &lt; respectively.

Expected behaviour

export_font_style should be supported and behave according to the docs.

**Comment by yusufani** [comment]
Hi, 
Is that possible to get background color in tables?

**Comment by raiyankamal** [comment]
Hi @ShayHill thanks for explaining. I came across this per chance. I sent a PR to fix the docs.

I don't have any additional support request at the moment. It's fine by me if you want to keep this thread open to collect suggestions from others.

**Comment by ShayHill** [comment]
Not with Docx2Python.

I’m trying to walk a line between getting out as much as possible (as long as it’s easily represented in text and doesn’t add a lot of noise).

However, Docx2Python will expose an intermediate layer between the input xml and text outputs. Within this layer, it will be straightforward to extract attributes like cell backgrounds. What makes it less than straightforward now is that docx files internally are several xml files that reference each other in ways lxml cannot follow.

-Shay

**Comment by ShayHill** [comment]
As always, thank you Raiyan.

**Comment by raiyankamal** [comment]
Are the colour values in font style guaranteed to be in 6 digit hex format? e.g. `ff000` for the colour red. Or is it possible to find colour values in 3 digit hex e.g. `f00` or in human readable colour name e.g. `red`?

**Comment by ShayHill** [comment]
That’s a create question. I just tried “F00”, “Red”, and “red”.

“F00” failed (result was black text). “Red” and “red” worked, so it seems the application will accept human-readable color values. However, I’m not sure how you’d enter one. For what it’s worth, I’ve run about 5500 docx files through Docx2Python and not encountered (as far as I can tell) and human-readable color values.

**Comment by raiyankamal** [comment]
Thanks for looking into it @ShayHill.

I have a font style related feature request: Can we have some markup for highlighted text?

[Here is a document](https://docs.google.com/document/d/1zBpx2rgI-vI2qwTpGJ2GZU4y2mbcPEOtBliAl488CAo/edit?usp=sharing) I created for testing. The second line has highlighted text. I would like to see this information somehow reflected in the resulting markup.

Currently this module produces `<font>` tags to present font colour. However, the `<font>` tag is [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font) from the web standards. Would it be better to use `<span>` instead?

**Comment by ShayHill** [comment]
> 
> 
> Thanks for looking into it @ShayHill.
> 
> I have a font style related feature request: Can we have some markup for highlighted text?
> 
> [Here is a document](https://docs.google.com/document/d/1zBpx2rgI-vI2qwTpGJ2GZU4y2mbcPEOtBliAl488CAo/edit?usp=sharing) I created for testing. The second line has highlighted text. I would like to see this information somehow reflected in the resulting markup.
> 
> Currently this module produces `<font>` tags to present font colour. However, the `<font>` tag is [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font) from the web standards. Would it be better to use `<span>` instead?

Docx2Python v2 supports the following:

output_tag | format

<i> italic
<b> bold
<u> underline
<s> strike
<del> double strike
<sup> superscript
<sub> subscript
<font style="font-variant: small-caps">small caps
<font style="text-transform:uppercase">all caps
<span style="background-color: yellow">highlighted yellow
<span style="background-color: green">highlighted green

If font tag is deprecated, then some of these tags are out of date. Still in alpha, so I'd love output-format suggestions.
