### ISSUE TITLE
Is it possible to "not use" any particular feature?

### ISSUE THREAD

**Issue by AayushSameerShah** [ShayHill/docx2python#48]
***I really have found this library useful 🙏🏻***

## Question 1️⃣ 
**Can I disable hyperlink extraction? If I want the link text itself, can I just disable this feature?** Like:  Instead of `<a href="http:/...">link text</a>` I just want `link text`.

## Question 2️⃣
**Can I get the number of pages? WITHOUT reading whole document?** I want the user to submit the doc which is only 5 pages long say, then without loading all contents, can I get the pages length?

Please guide, thanks.

**Comment by ShayHill** [comment]
Thank you for using docx2python.

1. There is not currently a way to suppress hyperlink extraction. I will think about how this might be accomplished simply. For now, I would recommend a regex to strip away the html tags.

2. I’ve had several requests for page count / page numbers. Unfortunately, word does not store page numbers or page breaks. These are assigned dynamically when the page renders, so there is no way to know the page count without re-implementing the hundreds-of-pages-long docx rendering specification.

Sent from my iPhone

On Dec 6, 2023, at 01:10, Aayush Shah ***@***.***> wrote:

﻿

I really have found this library useful 🙏🏻

1️⃣

Can I disable hyperlink extraction? If I want the link text itself, can I just disable this feature? Like: Instead of <a href="http:/...">link text</a> I just want link text.

2️⃣

Can I get the number of pages? WITHOUT reading whole document? I want the user to submit the doc which is only 5 pages long say, then without loading all contents, can I get the pages length?

Please guide, thanks.

**Comment by AayushSameerShah** [comment]
@ShayHill Thank you so much 😄 ✌🏻
